name: CMake-Linux

on:
  pull_request:
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build via script
      shell: bash
      run: bash scripts/cmake_build.sh

    - name: Run tests
      shell: bash
      run: bash scripts/run_tests.sh
