name: CMake-Windows

on:
  pull_request:
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      shell: bash
      run: cmake -S "${{ github.workspace }}" -B "${{ github.workspace }}/build" -DCMAKE_BUILD_TYPE="${{ env.BUILD_TYPE }}" -DCOMMANDLINE_LIBTYPE=SHARED

    - name: Build
      shell: bash
      run: cmake --build "${{ github.workspace }}/build" --parallel --config "${{ env.BUILD_TYPE }}"
